/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "auth": {
        "validation": {
            "email_required": string;
            "email_valid": string;
            "email_length": string;
            "password_required": string;
            "password_string": string;
            "password_length": string;
            "refresh_token_required": string;
            "refresh_token_string": string;
        };
        "errors": {
            "invalid_credentials": string;
            "invalid_token": string;
            "inactive_user": string;
            "access_denied": string;
            "insufficient_permissions": string;
            "unauthorized": string;
        };
    };
    "authors": {
        "validation": {
            "slug_required": string;
            "slug_string": string;
            "slug_length": string;
            "firstName_required": string;
            "firstName_string": string;
            "firstName_length": string;
            "lastName_required": string;
            "lastName_string": string;
            "lastName_length": string;
            "email_required": string;
            "email_valid": string;
            "email_length": string;
            "avatarUrl_valid": string;
        };
        "errors": {
            "not_found": string;
            "slug_exists": string;
            "email_exists": string;
            "name_exists": string;
        };
    };
    "languages": {
        "validation": {
            "code_required": string;
            "code_string": string;
            "code_length": string;
            "name_required": string;
            "name_string": string;
            "name_length": string;
            "is_default_boolean": string;
            "is_active_boolean": string;
        };
        "errors": {
            "not_found": string;
            "code_exists": string;
        };
    };
    "tags": {
        "validation": {
            "name_required": string;
            "name_string": string;
            "name_length": string;
            "slug_required": string;
            "slug_string": string;
            "slug_length": string;
            "languageId_required": string;
            "languageId_uuid": string;
            "id_uuid": string;
            "color_hex": string;
            "isActive_boolean": string;
            "translations_array": string;
            "search_string": string;
            "page_integer": string;
            "page_min": string;
            "limit_integer": string;
            "limit_min": string;
        };
        "errors": {
            "not_found": string;
            "slug_exists": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
