/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "authors": {
        "validation": {
            "slug_required": string;
            "slug_string": string;
            "slug_length": string;
            "firstName_required": string;
            "firstName_string": string;
            "firstName_length": string;
            "lastName_required": string;
            "lastName_string": string;
            "lastName_length": string;
            "email_required": string;
            "email_valid": string;
            "email_length": string;
            "avatarUrl_valid": string;
        };
        "errors": {
            "not_found": string;
            "slug_exists": string;
            "email_exists": string;
            "name_exists": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
